Repository JeschkeLab/DeerLab, pull requests merged in 2021-03, with the labels that each got.

#79 Add RIDME experiment models
  .github/workflows/docs_PR.yml
  deerlab/ex_models.py
  docsrc/source/models/ex_ridme1.rst
  docsrc/source/models/ex_ridme3.rst
  docsrc/source/models/ex_ridme5.rst
  docsrc/source/models/ex_ridme7.rst
  docsrc/source/modelsref.rst
  examples/plot_bootstrapped_parameter_distributions.py
  examples/plot_fitting_5pdeer.py
  test/test_fitsignal.py
Labels: enhancement

#83 Fix behaviour of deerload with 2D-datasets
  deerlab/deerload.py
Labels: bugfix

#67 Initialization strategies for multi-component models
  deerlab/fitmultimodel.py
  deerlab/utils/gof.py
  test/test_fitmultimodel.py
Labels: enhancement

#87 Improve interface of FitResult.plot() method
  deerlab/fitmultimodel.py
  deerlab/fitparamodel.py
  deerlab/fitregmodel.py
  deerlab/fitsignal.py
  deerlab/snlls.py
  test/test_fitmultimodel.py
  test/test_fitparamodel.py
  test/test_fitregmodel.py
  test/test_fitsignal.py
  test/test_snlls.py
Labels: enhancement

#73 Adjust parameters built-in start values for user-defined bounds in fitsignal
  deerlab/fitsignal.py
  test/test_fitsignal.py
Labels: bugfix

#88 Embed bootstrapping into fitsignal
  deerlab/fitsignal.py
  test/test_fitsignal.py
Labels: enhancement

#94 diststats: Implement compatibility with non-uniform P(r)
  deerlab/diststats.py
  test/test_diststats.py
Labels: enhancement

#96 docs: rework Getting Started guide (language, typos)
  deerlab/diststats.py
  docsrc/source/beginners_guide.rst
  test/test_diststats.py
Labels: documentation

#98 fitsignal: Merge uq and uqanalysis keyword arguments
  deerlab/fitsignal.py
  test/test_fitsignal.py
Labels: design

#101 Acceleration of fitting by avoiding model call overhead
  deerlab/bg_models.py
  deerlab/dd_models.py
  deerlab/ex_models.py
  deerlab/fitmultimodel.py
  deerlab/fitsignal.py
Labels: enhancement, performance

#104 docs: remove references to old functions fitbackground and backgroundstart
  docsrc/source/functions.rst
  docsrc/source/functions/backgroundstart.rst
  docsrc/source/functions/fitbackground.rst
Labels: documentation

#89 Update version and changelog
  CHANGELOG.md
  VERSION
Labels: release

#107 unify axis labeling: a.u.->arb.u.; P(r) -> P; V(t) -> V; [nm] -> (nm), etc.
  deerlab/deerload.py
  deerlab/fitmodel.py
  deerlab/fitmultimodel.py
  deerlab/fitregmodel.py
  docsrc/source/beginners_guide.rst
  docsrc/source/models/dd_circle.rst
  docsrc/source/models/dd_cos.rst
  docsrc/source/models/dd_gauss.rst
  docsrc/source/models/dd_gauss2.rst
  docsrc/source/models/dd_gauss3.rst
  docsrc/source/models/dd_gengauss.rst
  docsrc/source/models/dd_randcoil.rst
  docsrc/source/models/dd_rice.rst
  docsrc/source/models/dd_rice2.rst
  docsrc/source/models/dd_rice3.rst
  docsrc/source/models/dd_shell.rst
  docsrc/source/models/dd_shellshell.rst
  docsrc/source/models/dd_shellsphere.rst
  docsrc/source/models/dd_shellvoidshell.rst
  docsrc/source/models/dd_shellvoidsphere.rst
  docsrc/source/models/dd_skewgauss.rst
  docsrc/source/models/dd_sphere.rst
  docsrc/source/models/dd_spherepoint.rst
  docsrc/source/models/dd_spheresurf.rst
  docsrc/source/models/dd_triangle.rst
  docsrc/source/models/dd_uniform.rst
  docsrc/source/models/dd_wormchain.rst
  docsrc/source/models/dd_wormgauss.rst
  docsrc/source/models/ex_4pdeer.rst
  docsrc/source/models/ex_5pdeer.rst
  docsrc/source/models/ex_7pdeer.rst
  docsrc/source/models/ex_ovl4pdeer.rst
  docsrc/source/models/ex_ridme1.rst
  docsrc/source/models/ex_ridme3.rst
  docsrc/source/models/ex_ridme5.rst
  docsrc/source/models/ex_ridme7.rst
  examples/plot_analyzing_pake_pattern.py
  examples/plot_bootstrapped_parameter_distributions.py
  examples/plot_comparing_uncertainties_for_regularization.py
  examples/plot_emulating_deeranalysis_workflow.py
  examples/plot_extracting_gauss_constraints.py
  examples/plot_fitting_custom_kernel_with_snlls.py
  examples/plot_fitting_mixed_model.py
  examples/plot_globalfits_local_and_global_parameters.py
  examples/plot_multigauss_fitting_4pdeer.py
  examples/plot_param_uncertainty_propagation.py
  examples/plot_pseudotitration_parameter_free.py
  examples/plot_selecting_an_optimal_model.py
Labels: documentation

#106 docs: various edits
  deerlab/correctphase.py
  deerlab/correctscale.py
  deerlab/dipolarkernel.py
  deerlab/diststats.py
  deerlab/mixmodels.py
  deerlab/regoperator.py
  deerlab/regparamrange.py
  docsrc/README.md
  docsrc/source/basics.rst
  docsrc/source/firstscript.rst
  docsrc/source/fitting.rst
  docsrc/source/installation_failed.rst
  docsrc/source/modelsref.rst
  docsrc/source/preprocess.rst
  examples/plot_fitting_mixed_model.py
Labels: documentation

#112 Expose convergence criteria keyword arguments to all fit functions
  deerlab/fitmodel.py
  deerlab/fitmultimodel.py
  deerlab/fitregmodel.py
  deerlab/nnls.py
  test/test_fitmodel.py
  test/test_fitmultimodel.py
  test/test_fitregmodel.py
Labels: bugfix

#108 Implement arbitrary penalties for SNLLS & Pathway amplitudes contstraint
  deerlab/fitmodel.py
  deerlab/lsqcomponents.py
  deerlab/snlls.py
  deerlab/utils/utils.py
  test/test_fitmodel.py
  test/test_snlls.py
Labels: bugfix, design, enhancement, fundamental

#120 replace keyword uqanalysis with uq
  CHANGELOG.md
  deerlab/correctscale.py
  deerlab/fitmodel.py
  deerlab/fitmultimodel.py
  deerlab/fitparamodel.py
  deerlab/fitregmodel.py
  deerlab/snlls.py
  examples/plot_emulating_deeranalysis_workflow.py
  examples/plot_fitting_4pdeer.py
  examples/plot_fitting_5pdeer.py
  examples/plot_fitting_mixed_model.py
  test/test_fitmultimodel.py
  test/test_snlls.py
Labels: design

#119 dipolarkernel: change B default to None
  deerlab/dipolarkernel.py
  test/test_dipolarkernel.py
Labels: enhancement

#121 Add testing of uncertainty against results from `lmfit` package
  deerlab/fitregmodel.py
  deerlab/snlls.py
  test/test_fitparamodel.py
  test/test_fitregmodel.py
  test/test_snlls.py
Labels: enhancement

#123 Rename `UncerQuant` class to `UQResult`
  deerlab/__init__.py
  deerlab/bootan.py
  deerlab/classes.py
  deerlab/diststats.py
  deerlab/fitmodel.py
  deerlab/fitmultimodel.py
  deerlab/fitparamodel.py
  deerlab/fitregmodel.py
  deerlab/snlls.py
  docsrc/source/functions/UQResult.rst
  docsrc/source/functions/UncertQuant.rst
  docsrc/source/uncertainty.rst
Labels: design

#122 Further minor edits to the documentation
  README.md
  docsrc/source/beginners_guide.rst
  docsrc/source/installation.rst
  setup.py
Labels: documentation

#129 fitparamodel: rename rescale keyword
  CHANGELOG.md
  deerlab/correctscale.py
  deerlab/fitparamodel.py
  examples/plot_emulating_deeranalysis_workflow.py
  examples/plot_extracting_gauss_constraints.py
  test/test_fitparamodel.py
Labels: enhancement

#133 snlls: Enable scale preconditioning to avoid scaling issues in uncertainty quantification
  deerlab/snlls.py
  test/test_snlls.py
Labels: bugfix
