Repository JeschkeLab/DeerLab, pull requests merged in 2021-04, with the labels that each got.

#134 Return model fits and uncertainties in fit functions
  CHANGELOG.md
  deerlab/fitmodel.py
  deerlab/fitmultimodel.py
  deerlab/fitparamodel.py
  deerlab/fitregmodel.py
  deerlab/snlls.py
  test/test_diststats.py
  test/test_fitmultimodel.py
  test/test_fitparamodel.py
  test/test_fitregmodel.py
  test/test_snlls.py
Labels: enhancement

#137 fitmodel: remove regtype optional argument
  deerlab/fitmodel.py
Labels: design

#131 correctphase: optimize based on integral of real component
  CHANGELOG.md
  deerlab/correctphase.py
  deerlab/noiselevel.py
  docsrc/source/beginners_guide.rst
  test/test_correctphase.py
Labels: enhancement

#138 dipolarkernel: new design for keyword arguments
  deerlab/correctscale.py
  deerlab/dipolarbackground.py
  deerlab/dipolarkernel.py
  deerlab/fitmodel.py
  deerlab/fitmultimodel.py
  docsrc/source/basics.rst
  examples/plot_analyzing_pake_pattern.py
  examples/plot_bootstrapped_parameter_distributions.py
  examples/plot_comparing_uncertainties_for_regularization.py
  examples/plot_emulating_deeranalysis_workflow.py
  examples/plot_extracting_gauss_constraints.py
  examples/plot_fitting_4pdeer.py
  examples/plot_fitting_5pdeer.py
  examples/plot_fitting_custom_kernel_with_snlls.py
  examples/plot_multigauss_fitting_4pdeer.py
  examples/plot_param_uncertainty_propagation.py
  examples/plot_pseudotitration_parameter_free.py
  test/test_correctscale.py
  test/test_dipolarbackground.py
  test/test_dipolarkernel.py
  test/test_fitmodel.py
  test/test_fitmultimodel.py
  test/test_fitregmodel.py
  test/test_noiselevel.py
  test/test_snlls.py
Labels: design

#141 Speed up slow tests by reducing P(r) resolution
  test/test_dipolarbackground.py
  test/test_fitmodel.py
  test/test_fitmultimodel.py
  test/test_snlls.py
Labels: performance

#143 Implement models metadata as function attributes
  CHANGELOG.md
  deerlab/bg_models.py
  deerlab/dd_models.py
  deerlab/ex_models.py
  deerlab/fitmodel.py
  deerlab/fitmultimodel.py
  deerlab/mixmodels.py
  test/test_bgmodels.py
  test/test_ddmodels.py
  test/test_fitmodel.py
  test/test_fitparamodel.py
Labels: design

#144 Add uncertainty analysis to global fit examples missing it
  deerlab/classes.py
  deerlab/fitparamodel.py
  deerlab/snlls.py
  examples/ex_globalfits_local_and_global_parameters.py
  examples/ex_pseudotitration_parameter_free.py
Labels: bugfix, documentation

#146 fix a few bugs in dd models; add test
  deerlab/dd_models.py
  test/test_ddmodels.py
Labels: bugfix

#149 Properly implement post-definition manipulations of `UQResult`
  deerlab/classes.py
  deerlab/fitmodel.py
  deerlab/fitmultimodel.py
  deerlab/fitregmodel.py
  deerlab/snlls.py
Labels: bugfix

#148 New examples and updates
  deerlab/fitmodel.py
  docsrc/source/conf.py
  examples/advanced/README.rst
  examples/advanced/ex_comparing_uncertainties_for_regularization.py
  examples/advanced/ex_extracting_gauss_constraints.py
  examples/advanced/ex_fitting_custom_kernel_with_snlls.py
  examples/advanced/ex_fitting_mixed_model.py
  examples/advanced/ex_globalfits_local_and_global_parameters.py
  examples/advanced/ex_multigauss_fitting_4pdeer.py
  examples/advanced/ex_param_uncertainty_propagation.py
  examples/advanced/ex_pseudotitration_parameter_free.py
  examples/advanced/manipulating_graphics.py
  examples/basic/README.rst
  examples/basic/ex_bootstrapping.py
  examples/basic/ex_fitting_4pdeer.py
  examples/basic/ex_fitting_4pdeer_2p1.py
  examples/basic/ex_fitting_5pdeer.py
  examples/basic/ex_global_different_deer.py
  examples/basic/ex_global_fitting_4pdeer.py
  examples/basic/ex_restraints_4pdeer.py
  examples/ex_fitting_4pdeer.py
  examples/ex_fitting_5pdeer.py
  examples/other/README.rst
  examples/other/ex_analyzing_pake_pattern.py
  examples/other/ex_bootstrapped_parameter_distributions.py
  examples/other/ex_emulating_deeranalysis_workflow.py
  examples/other/ex_selecting_an_optimal_model.py
Labels: bugfix, documentation

#154 Implement `join()` method to combine multiple uncertainty quantifications
  deerlab/classes.py
  examples/advanced/ex_pseudotitration_parameter_free.py
Labels: enhancement

#157 Distribute DeerLab via Anaconda
  .gitignore
  conda.recipe/build.bat
  conda.recipe/meta.yaml
  conda.recipe/package_conda.bat
Labels: enhancement

#155 docs: Update installation instructions
  docsrc/source/installation.rst
Labels: documentation

#158 Rename example with proper prefix
  examples/advanced/ex_manipulating_graphics.py
Labels: bugfix, documentation

#159 Implement new noise estimation method & use it to avoid circular dependency in chi2red estimation
  deerlab/fitregmodel.py
  deerlab/noiselevel.py
  deerlab/utils/gof.py
  test/test_fitmultimodel.py
  test/test_fitregmodel.py
  test/test_noiselevel.py
  test/test_snlls.py
Labels: bugfix, design, enhancement

#160 Prepare release v0.13.0
  CHANGELOG.md
  VERSION
  conda.recipe/meta.yaml
Labels: release

#166 Fix prescaling of data and vanishing confidence intervals in `snlls`
  deerlab/fitregmodel.py
  deerlab/utils/utils.py
  test/test_fitregmodel.py
  test/test_snlls.py
Labels: bugfix

#164 deerload: Fix bug when loading BES3T files with entries in manipulation history layer
  deerlab/deerload.py
  test/data/data_1d.DSC
  test/data/data_1d.DTA
  test/data/data_2d.DSC
  test/data/data_2d.DTA
  test/data/data_multi_lab1.DSC
  test/data/data_multi_lab1.DTA
  test/data/data_multi_lab2.DSC
  test/data/data_multi_lab2.DTA
  test/data/data_multi_lab3.DSC
  test/data/data_multi_lab3.DTA
  test/data/data_multi_lab4.DSC
  test/data/data_multi_lab4.DTA
  test/data/data_multi_lab5.DSC
  test/data/data_multi_lab5.DTA
  test/data/data_sparse.DSC
  test/data/data_sparse.DTA
  test/data/data_sparse.XGF
  test/test_deerload.py
Labels: bugfix
