Repository JeschkeLab/DeerLab, pull requests merged in 2021-07, with the labels that each got.

#188 `snlls`: Fix violation of boundaries due to float-point round-off errors
  deerlab/snlls.py
  deerlab/utils/utils.py
Labels: bug, bugfix

#190 docs: Fix automated example plots in the models reference
  deerlab/dd_models.py
Labels: bugfix, documentation

#191 Patch v0.13.2
  .github/actions/conda_build_publish_package/Dockerfile
  .github/actions/conda_build_publish_package/README.md
  .github/actions/conda_build_publish_package/action.yml
  .github/actions/conda_build_publish_package/entrypoint.sh
  .github/workflows/codeql-analysis.yml
  .github/workflows/package_upload.yml
  CHANGELOG.md
  VERSION
  conda.recipe/build.sh
  conda.recipe/meta.yaml
  deerlab/dd_models.py
  deerlab/snlls.py
  deerlab/utils/utils.py
  examples/basic/ex_bootstrapping.py
  examples/basic/ex_fitting_4pdeer.py
  examples/basic/ex_fitting_4pdeer_2p1.py
  examples/basic/ex_fitting_5pdeer.py
  examples/basic/ex_global_different_deer.py
  examples/basic/ex_global_fitting_4pdeer.py
  examples/basic/ex_restraints_4pdeer.py
  setup.py
Labels: release

#194 docs: remove absence of orientation selection from DeerLab's assumptions
  docsrc/source/theory.rst
Labels: docs

#196 Fix build and packaging action workflow
  .github/workflows/package_upload.yml
Labels: bugfix

#197 `snlls`: Allow passing multiple custom penalty functions
  deerlab/snlls.py
  test/test_snlls.py
Labels: enhancement

#203 `dipolarkernel`: fix bug in orisel integration with 'integral' method
  deerlab/dipolarkernel.py
Labels: bugfix

#202 docs/bg_models: Correct spin concentration parameter description
  deerlab/bg_models.py
Labels: docs

#204 regoperator: add option to exclude edges in derivative
  deerlab/regoperator.py
  test/test_regoperator.py
Labels: enhancement

#209 docs/beginners_guide: fix space leading to bug in Latex rendering
  docsrc/source/beginners_guide.rst
Labels: docs

#211 Skip unit test if an error with the Tk backend of Matplotlib occurs
  deerlab/utils/utils.py
  test/test_fitmodel.py
  test/test_fitmultimodel.py
  test/test_fitparamodel.py
  test/test_fitregmodel.py
  test/test_regoperator.py
  test/test_snlls.py
Labels: bugfix

#213 Allow specification of the noise levels and fix goodness-of-fit throughout DeerLab
  deerlab/fitmodel.py
  deerlab/fitmultimodel.py
  deerlab/fitparamodel.py
  deerlab/fitregmodel.py
  deerlab/selregparam.py
  deerlab/snlls.py
  deerlab/utils/gof.py
  deerlab/utils/utils.py
  test/test_fitmodel.py
  test/test_fitmultimodel.py
  test/test_fitparamodel.py
  test/test_fitregmodel.py
  test/test_snlls.py
Labels: bugfix, enhancement

#215 `docs/dd_models`: correct math in Latex equations
  deerlab/dd_models.py
Labels: docs
