Repository JeschkeLab/DeerLab, pull requests merged in 2022-03, with the labels that each got.

#279 `correctphase` refactor
  deerlab/correctphase.py
  test/test_correctphase.py
Labels: enhancement

#276 require std dev input for `whitegaussnoise`
  deerlab/whitegaussnoise.py
  test/test_model_class.py
  test/test_whitegaussnoise.py
Labels: enhancement

#280 gauss: change width to std
  deerlab/dd_models.py
  docsrc/source/basics.rst
  docsrc/source/fitting_guide.rst
  docsrc/source/modelling_guide.rst
  examples/advanced/ex_droplets_model.py
  examples/advanced/ex_extracting_gauss_constraints.py
  examples/advanced/ex_global_twostates_parametric.py
  test/test_dipolarmodel.py
  test/test_model_class.py
  test/test_model_lincombine.py
  test/test_model_link.py
  test/test_model_merge.py
  test/test_model_penalty.py
  test/test_model_relate.py
  test/test_profile_analysis.py
  test/test_snlls.py
  test/test_snlls_nlls.py
  test/test_snlls_rlls.py
Labels: design

#281 change "units" to "unit"
  deerlab/bg_models.py
  deerlab/dd_models.py
  deerlab/dipolarmodel.py
  deerlab/ex_models.py
  deerlab/model.py
Labels: minor

#285 multigauss: small fix
  deerlab/dd_models.py
Labels: bugfix

#287 backgrounds: refactor, bug fixes, work on doc
  deerlab/__init__.py
  deerlab/bg_models.py
  deerlab/dipolarbackground.py
  docsrc/source/dipolar_guide_fitting.rst
  docsrc/source/dipolar_guide_modelling.rst
  test/test_bgmodels.py
  test/test_dipolarbackground.py
Labels: docs, enhancement, bugfix, refactor

#288 simplify model evaluation code
  deerlab/model.py
Labels: refactor

#289 remove unused ex_models file
  deerlab/__init__.py
  deerlab/dipolarmodel.py
  deerlab/ex_models.py
Labels: bugfix

#291 Update multiple information throughout
  LICENSE
  README.md
  deerlab/bg_models.py
  deerlab/bootstrap_analysis.py
  deerlab/classes.py
  deerlab/correctzerotime.py
  deerlab/dd_models.py
  deerlab/dipolarbackground.py
  deerlab/dipolarkernel.py
  deerlab/dipolarmodel.py
  deerlab/distancerange.py
  deerlab/diststats.py
  deerlab/fftspec.py
  deerlab/model.py
  deerlab/noiselevel.py
  deerlab/profile_analysis.py
  deerlab/regoperator.py
  deerlab/selregparam.py
  deerlab/solvers.py
  deerlab/utils/gof.py
  docsrc/source/conf.py
  docsrc/source/installation.rst
  docsrc/source/others.rst
  setup.py
Labels: dev

#297 Implement normalization conditions for model linear parameters
  deerlab/classes.py
  deerlab/dd_models.py
  deerlab/dipolarmodel.py
  deerlab/model.py
  docsrc/source/dipolar_guide_fitting.rst
  docsrc/source/modelling_guide.rst
  test/test_dipolarmodel.py
  test/test_model_class.py
  test/test_model_lincombine.py
  test/test_model_merge.py
Labels: enhancement, design

#299 Implement dropdown navigation bar for the documentation
  docsrc/source/_static/theme_override.css
  docsrc/source/_templates/nav.html
  docsrc/source/conf.py
  docsrc/source/index.rst
  docsrc/source/license.rst
  docsrc/source/support.rst
  docsrc/source/user_guide.rst
Labels: docs, enhancement, design

#295 Add `CITATION.cff`
  CITATION.cff
Labels: dev
