Repository JeschkeLab/DeerLab, pull requests merged in 2023-08, with the labels that each got.

#437 refactor basic sim examples
  examples/basic_simulations/ex_simulate_4pdeer.py
  examples/basic_simulations/ex_simulate_5pdeer.py
  examples/basic_simulations/ex_simulate_basic_4pdeer.py
Labels: enhancement, refactor

#447 Prepare v1.1.0
  .github/workflows/deploy_ghpages.yml
  .github/workflows/docs_PR.yml
  .github/workflows/examples_PR.yml
  VERSION
  docsrc/source/changelog.rst
Labels: release

#454 Fix issue in evaluate function
  deerlab/fitresult.py
Labels: bugfix

#455 Increase version number and update changelog
  VERSION
  docsrc/source/changelog.rst
Labels: bugfix, release
